//USUARIO
export const REGISTER_USUARIO = "REGISTER_USUARIO"
export const LOGIN_USUARIO = "LOGIN_USUARIO"
export const LOGOUT_USUARIO= "LOGOUT_USUARIO"

//CATEGORIAS
export const OBTENER_CATEGORIAS = "OBTENER_CATEGORIAS"
export const CREAR_CATEGORIA = "CREAR_CATEGORIA"
export const EDITAR_CATEGORIA = "EDITAR_CATEGORIA"
export const ELIMINAR_CATEGORIA = "ELIMINAR_CATEGORIA"

//GASTOS