//USUARIO
export const REGISTER_USUARIO = "REGISTER_USUARIO"
export const LOGIN_USUARIO = "LOGIN_USUARIO"
export const LOGOUT_USUARIO = "LOGOUT_USUARIO"
export const FORGOT_PASSWORD = "FORGOT_PASSWORD"
export const CHANGE_PASSWORD = "CHANGE_PASSWORD"

//CATEGORIAS
export const OBTENER_CATEGORIAS = "OBTENER_CATEGORIAS"
export const CREAR_CATEGORIA = "CREAR_CATEGORIA"
export const ACTUALIZAR_CATEGORIA = "ACTUALIZAR_CATEGORIA"
export const ELIMINAR_CATEGORIA = "ELIMINAR_CATEGORIA"

//GASTOS
export const OBTENER_GASTOS = "OBTENER_GASTOS"
export const CREAR_GASTO = "CREAR_GASTO"
export const ACTUALIZAR_GASTO = "ACTUALIZAR_GASTO"
export const ELIMINAR_GASTO = "ELIMINAR_GASTO"